name: Crawl Sites

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
          ~/.cache/chromium
          ~/.local/share/crawl4ai
        key: ${{ runner.os }}-browsers-${{ hashFiles('requirements.txt') }}-v1
        restore-keys: |
          ${{ runner.os }}-browsers-${{ hashFiles('requirements.txt') }}-
          ${{ runner.os }}-browsers-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Crawl4ai post install
      run: |
        if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
          echo "Cache miss - Installing browsers and dependencies"
          crawl4ai-setup
        else
          echo "Cache hit - Browsers already cached, installing only system dependencies"
          # Run crawl4ai-setup with minimal installation if possible
          # If crawl4ai-setup doesn't support conditional installation, we still run it
          # but it should be faster as browsers are already cached
          crawl4ai-setup
        fi

    - name: Verify crawl4ai
      run: crawl4ai-doctor

    - name: Run blog crawler
      run: python crawl_blog.py

    - name: Run docs crawler
      run: python crawl_docs.py

    - name: Run desci codes crawler
      run: python crawl_desci_codes.py

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Check for changes and commit
      run: |
        # Check if files exist and have changes, or if they're new files
        git add data/molecule_blog.json data/molecule_docs.json data/desci_codes.json

        # Check if there are any changes staged (this handles both modified and new files)
        if git diff --cached --quiet; then
          echo "No changes detected in crawled data files"
          exit 0
        fi

        # Get current date and time
        CURRENT_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

        # Commit the files
        git commit -m "New crawl @ $CURRENT_DATE [skip ci]"

        echo "Changes committed successfully"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
